### PR TITLE
Improve demos section & add Sketchpad.cc page.

### PR DESCRIPTION
**Pull request by jcxldn**

### CODE REVIEW

**Comment by domdomegg** [comment]
Url to sketchpad is

[clsb.sketchpad.cc](http://clsb.sketchpad.cc/)

I *think* there is some way to embed them easily, would be good to have a couple demos direct on the site

**Comment by jcxldn** [comment]
We can embed them but I chose not to as they do not play nicely with the firewall @ sch.

**Comment by domdomegg** [comment]
You sure they don't embed nicely? Think it's should be unblocked.

Also use the heading Processing.js instead of Sketchpad

Thanks :)

**Comment by jcxldn** [comment]
I did try to embed it directly, but even with a bit of tweaking, all I got was file not found and server not responding errors from sophos.

**Comment by domdomegg** [comment]
Did it work when at home?

**Comment by domdomegg** [comment]
Can you send me a branch with it just to test

**Pull request closed without merging**
