### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by jcxldn**
I thought this needed a README, (one reason is because when i typed it in on my phone it would redirect to the repo page instead of the site)

It basically says:

**CLSB Programming**
The CLSB Programming Website Repository.
[Click here to go to the site.](https://clsb-programming.github.io/)

### CODE REVIEW

**Comment by domdomegg** [comment]
ngl I think the view counter is tacky - thoughts @VinuJ ?

good idea on the readme

**Comment by jcxldn** [comment]
I'll get rid of it.

**Comment by jcxldn** [comment]
Removed.

**Comment by domdomegg** [comment]
Nice, I appreciate the work on the README

**Pull request merged**
