### PR TITLE
Add Mobile Version Tag.

### PR DESCRIPTION
**Pull request by jcxldn**

### CODE REVIEW

**Comment by domdomegg** [comment]
Ummm.. why? Surely they can just see it works on their phone. Might be an idea to hide parts of the title that aren't relevant/display a different title

Also an easier and better support solution might be to set display: none in general, then display: block in mobile media query.

**Comment by jcxldn** [comment]
Explain that last part.

**Comment by domdomegg** [comment]
With your mobile version tag, rather than using the `:after` selector and `content` property which are often not supported by older and mobile browsers, you could use the simple `display: none` in the main css, but in the mobile query selector set it to `display: block`, so that on mobile it is actually shown.

But yea, what I had in mind was something like:

Desktop:
screenshot from 2017-01-27 19-51-12

Mobile:
screenshot from 2017-01-27 19-52-10

**Comment by domdomegg** [comment]
BTW if you still don't understand what I mean don't hesitate to comment again / contact me on discord/steam

**Pull request closed without merging**
