### PR TITLE
Update Links

### PR DESCRIPTION
**Pull request by jcxldn**
You know you don't have to put the full address in right?

Eg = Homepage = "/"

### CODE REVIEW

**Comment by domdomegg** [comment]
Ya, just might break it if I decide to move the page elsewhere. You sure the link to Vinu's page works as intended - I would have thought it should be `/vinu` or `../vinu` ?

**Comment by jcxldn** [comment]
You did just vinu in the Homepage. If you're unsure do ~vinu or something

**Comment by domdomegg** [comment]
The links are all relative

/ Is the top level of the website.
From the homepage (index.html) to Vinu it's just "vinu" but from my page which is in the "adam" folder it's the folder above then in the folder called vinu. So it should be:

../vinu (go up a folder and then into vinu's folder
Or
/vinu (go to the top of the website then into vinu's folder)

**Comment by domdomegg** [comment]
Also aren't you supposed to have lessons or something?

**Comment by jcxldn** [comment]
Something called delays on trains.
If I have time I'll do the links later.

**Comment by jcxldn** [comment]
Happy?
All proper formatting and did /index.html

**Comment by domdomegg** [comment]
Good - but you could have left out the index.html as that's the default file that webservers will usually look for.

**Comment by jcxldn** [comment]
I know but just personal preference

**Pull request merged**
