### PR TITLE
Create cryptanalysis tools

### PR DESCRIPTION
**Pull request by domdomegg**
And add links to the appropriate places

### CODE REVIEW

**Comment by domdomegg** [comment]
@VinuJ

**Comment by jcxldn** [comment]
If you want someone 2 look at it, assign it to them.

**Comment by jcxldn** [comment]
Ok. Merge conflict. 👎  Well that sucks.

**Comment by domdomegg** [comment]
oh cause of the links... dammit.

**Comment by domdomegg** [comment]
also @VinuJ doesn't seem to be doing anything :/

**Comment by domdomegg** [comment]
Still amazed github doesn't have a merge conflict resolving tool - fixed it though.

**Pull request merged**
